services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-}
    container_name: vix_tool
    restart: unless-stopped
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-}
    networks:
      - vix_frontend_net

networks:
  vix_frontend_net:
    name: vix_frontend_net
    driver: bridge
